### ISSUE TITLE
Severe bug: removing files if .last-sync acts towards different sync-directory.

### ISSUE THREAD

**Issue by teson2000** [sergio-bobillier/php-file-sync#2]
There's something problematic with set setup if you need to sync different directories.
**(Actually it's quite awful - I just lost >6000 files, but having backups working for me now...)**

Suggestions (read: urgent):
- The console-script is currently a controller with lots of code in it. Move that code to the main class or someplace else.
- Have the nobrainer-config-settings _inside_ the minimized console-script.
- And name the .last-sync-file to the name of the calling script.

Thus, if I sync two different directories using syncMyDir1.php and syncMyDir2.php (each holding the minimal config and require()), I get .last-sync-syncMyDir1 etc.

**Comment by sergio-bobillier** [comment]
The console script is designed to synchronize only ONE directory because it always loads the settings from settings.php and stores the time of the last synchronization in one single file: `.last-sync` and doesn't accept any arguments to change the synchronized paths.

If you want to use the script to synchronize different directories I suggest you create your own script and instantiate the `File_Synchronizer` class instead of using the console script directly. You can pass the configuration as you need. For example, you can use the `set_last_sync_time` function to set the time of the last synchronization and you can store that value wherever you like, even a database.

However I appreciate your opinion and I will consider changing the script so that it can synchronize different paths.

**Comment by teson2000** [comment]
Thank you for your support and a fine script.

Best regards,
/Tjelvar Eriksson

2015-04-24 3:00 GMT+02:00 Sergio Bobillier notifications@github.com:
